import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 *
 */
public class OraclePaddingClient {
    static final String ENCRYPTED_MESSAGE = "5ca00ff4c878d61e1edbf1700618fb287c21578c0580965dad57f70636ea402fa0017c4acc82717730565174e2e3f713d3921bab07cba15f3197b87976525ce4";
    static final String TARGET_IP = "localhost";
    static final Integer TARGET_PORT = 8080;
    static final String TARGET_PATH = "/cbc/po";

    static final Boolean RESPONSEIFERROR = false;

    CloseableHttpClient hgOraclePadClient = HttpClients.createDefault();

    /**
     * Turns array of bytes into string hex representation
     *
     * @param buf Array of bytes to convert to hex string
     * @return Generated hex string
     */
    public static String stringAsHexFromBytes(byte buf[]) {
        StringBuilder strbuf = new StringBuilder(buf.length * 2);
        int i;
        for (i = 0; i < buf.length; i++) {
            if (((int) buf[i] & 0xff) < 0x10) {
                strbuf.append("0");
            }
            strbuf.append(Long.toString((int) buf[i] & 0xff, 16));
        }
        return strbuf.toString();
    }

    /**
     * Turns HEx representation into array of bytes
     *
     * @param hex String Hex representation to convert to Array of bytes
     * @return Generated byte array
     */
    public static byte[] bytesFromStringAsHex(String hex) {
        byte[] buf;

        Integer hexlen = hex.length() / 2;
        buf = new byte[hexlen];
        int i;
        for (i = 0; i < hexlen; i++) {
            String str = hex.substring(i * 2, i * 2 + 2);

            buf[i] = (byte) ((Character.digit(str.charAt(0), 16) << 4) + Character.digit(str.charAt(1), 16));
        }
        return buf;
    }

    public static void main(String[] args) {
        OraclePaddingClient opc = new OraclePaddingClient();

        try {
            System.out.println("Server responded : " + opc.query(ENCRYPTED_MESSAGE));
        } catch (Exception e) {
            System.out.print("Exception from server");
            e.printStackTrace();
        }
    }

    /**
     * Sends query to Http server
     *
     * @param q String passed as argument to uri
     * @return Server Response Status Code
     */
    public boolean query(String q) throws IOException, URISyntaxException {
        URI uri = new URIBuilder()
                .setScheme("http")
                .setHost(TARGET_IP)
                .setPort(TARGET_PORT)
                .setPath(TARGET_PATH)
                .setParameter("path", q)
                .build();

        HttpGet httpget = new HttpGet(uri);
        CloseableHttpResponse response = hgOraclePadClient.execute(httpget);

        int statuscode = response.getStatusLine().getStatusCode();
        response.close();

        boolean isPaddingGood;
        switch (statuscode) {
            case 200: // legitimate message
                isPaddingGood = true;
                break;
            case 404: // good padding, bad request
                isPaddingGood = true;
                break;
            case 403: // wrong padding
                isPaddingGood = RESPONSEIFERROR;
                break;
            default: // server issue
                isPaddingGood = true;
        }
        return isPaddingGood;
    }
}

